routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\ProductController;

Route::get('/', function () {
    //return view('welcome');
    return view('admin.pages.product.list');
});
Route::group(['prefix'=>'admin'],function(){
    Route::resource('brand','BrandController');
    Route::resource('product', 'ProductController');
});

app/Models/Brand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    //
    protected $table ='brands';
    protected $fillable=['brand_name','address',];
    public function product(){
        // lay ra cac san pham cung thuong hieu
        return $this->hasMany('App\Models\Product','brand_id','id');
    }
}

app/Http/Controllers/BrandController.php
<?php

namespace App\Http\Controllers;

use App\Models\Brand;
use Illuminate\Http\Request;
use App\Http\Requests\StoreBrandRequest;
use App\Http\Requests\UpdateBrandRequest;
use Validator;
class BrandController extends Controller
{

    public function index()
    {
        //
        $brand = Brand::all();
        return view('admin.pages.brand.list',['brand'=>$brand]);
    }


    public function create()
    {
        //
        return view('admin.pages.brand.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreBrandRequest $request)
    {
       Brand::Create([
           'brand_name'=> $request-> brand,
            'address' => $request -> address,
       ]);
       return redirect()->route('brand.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
       
    }
}

resources/views/admin/pages/brand/add.blade.php
@extends('admin.layout.master')


@section('title')
    add new brand
@endsection


@section('content')
    <div class="card shadow mb-4">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary"> Add New Brand</h6>
            </div>
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="row" style="margin: 5px">

                <div class="col-lg-5">
                    <form role="form" action="{{ route('brand.store') }}" method="post">
                        @csrf
                        <fieldset class="form-group">
                            <label>Brand_name</label>
                            <input class="form-control" name="brand" >
                        </fieldset>
                        <fieldset class="form-group">
                            <label>Address</label>
                            <input class="form-control" name ="address">
                        </fieldset>


                        <button type="submit" class="btn btn-success">Add</button>
                        <button type="reset" class="btn btn-primary">Reset</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/pages/brand/list.blade.php
@extends('admin.layout.master')


@section('title')
    list brand

@endsection


@section('content')
    <div class="container-fluid">

        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add">Add Brand</button>

            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>STT</th>
                                <th>ID</th>
                                <th>BRAND_NAME</th>
                                <th>ADDRESS</th>
                                <th>Chỉnh sửa</th>
                            </tr>
                        </thead>

                        <tbody>
                        @foreach($brand as $key=>$value)
                            <tr>
                                <td>{{ $key +1 }}</td>
                                <td>{{$value->id}}</td>
                                <td>{{$value->brand_name}}</td>
                                <td>{{$value->address}}</td>
                                <td>
                                    <button class="btn btn-primary edit" data-toggle="modal" data-target="#edit" type="button" data-id="{{$value->id}}"><i class="fas fa-edit"></i></button>
                                    <button class="btn btn-danger delete" data-toggle="modal" data-target="#delete" type="button" data-id="{{$value->id}}"><i class="fas fa-trash-alt"></i></button>
                                </td>
                            </tr>
                        </tbody>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>

<!-- add modal -->
<div class="modal fade" id="add" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Chỉnh sửa:<span class="title"></span></h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row" style="margin: 5px">
                        <div class="col-lg-12">
                            <form role="form" >
                                <fieldset class="form-group">
                                    <label>Brand_name</label>
                                    <input class="form-control brand" name="brand" id="brand" >
                                    <span class="error" style="color:green ;font-size: 1rem; "></span>
                                </fieldset>
                                <fieldset class="form-group">
                                    <label>Address</label>
                                    <input class="form-control address" name="address" >
                                    <span class="error" style="color:green ;font-size: 1rem; "></span>
                                </fieldset>

                            </form>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success addBrand">Save</button>
                    <button type="reset" class="btn btn-primary ">Làm Lại</button>

                </div>
            </div>
        </div>
    </div>


<!-- end add modal -->



{{--    edit modal--}}
    <div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Chỉnh sửa:<span class="title"></span></h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row" style="margin: 5px">
                        <div class="col-lg-12">
                            <form role="form" >
                                <fieldset class="form-group">
                                    <label>Brand_name</label>
                                    <input class="form-control brand" name="brand" id="brand" >
                                    <span class="error" style="color:green ;font-size: 1rem; "></span>
                                </fieldset>
                                <fieldset class="form-group">
                                    <label>Address</label>
                                    <input class="form-control address" name="address" id="address" >
                                    <span class="error" style="color:green ;font-size: 1rem; "></span>
                                </fieldset>

                            </form>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success update">Save</button>
                    <button type="reset" class="btn btn-primary ">Làm Lại</button>

                </div>
            </div>
        </div>
    </div>
{{--    end edit modal--}}

{{--    delete modal--}}
    <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Bạn có muốn xóa ?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body" style="margin-left: 183px;">
                    <button type="button" class="btn btn-success delete">Có</button>
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Không</button>
                    <div>
                    </div>
                </div>
            </div>

{{--    end delete modal--}}
@endsection