routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\ProductController;

Route::get('/', function () {
    //return view('welcome');
    return view('admin.pages.product.list');
});
Route::group(['prefix'=>'admin'],function(){
    Route::resource('brand','BrandController');
    Route::resource('product', 'ProductController');
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
    protected $table = 'products';
    protected $fillable=['name_product','color_id','brand_id','price'];
    public function Brand(){
        return $this->belongsTo('App\Models\Brand');
    }
    public function Color(){
        return $this->belongsTo('App\Models\Color');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;
use App\Models\Brand;
use App\Models\Color;
use App\Http\Requests\StoreProductRequest;
use Validator;
class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

        $product = Product::paginate(5);
        return view('admin.pages.product.list',compact('product'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
       $data['brand']= Brand::all();
       $data['color']= Color::all();

        return view('admin.pages.product.add',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProductRequest $request)
    {
        //
       // dd($request);
        
      

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
       
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        //
        


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        //
       
    }
}

resources/views/admin/pages/product/add.blade.php
@extends('admin.layout.master')


@section('title')
    add new Product
@endsection


@section('content')
    <div class="card shadow mb-4">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary"> Add New Product</h6>
            </div>
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="row" style="margin: 5px">

                <div class="col-lg-5">
                    <form role="form" action="{{ route('product.store') }}" method="post" >
                        @csrf
                        <fieldset class="form-group">
                            <label>Product_name</label>
                            <input class="form-control" name="name" >
                        </fieldset>
                        <fieldset class="form-group">
                            <label>Color</label>
                            <select class="form-control" name="color">
                                @foreach($color as $col)
                                <option value="{{$col->id}}">{{ $col->name_color }}</option>
                                @endforeach
                            </select>
                        </fieldset>
                        <fieldset class="form-group">
                            <label>brand</label>
                           <select class="form-control" name="brand">
                               @foreach($brand as $bra)
                               <option value="{{ $bra->id }}">{{ $bra->brand_name }}</option>
                               @endforeach
                           </select>
                        </fieldset>
                        <fieldset class="form-group">
                            <label>price</label>
                            <input class="form-control" name ="price">
                        </fieldset>


                        <button type="submit" class="btn btn-success">Add</button>
                        <button type="reset" class="btn btn-primary">Reset</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/pages/product/list.blade.php
@extends('admin.layout.master')


@section('title')
    list brand

@endsection


@section('content')
    <div class="container-fluid">

        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary"></h6>
                <button type="button" class="btn btn-primary">Add Product</button>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>STT</th>
                            <th>ID</th>
                            <th>NAME</th>
                            <th>Color</th>
                            <th>Brand</th>
                            <th>Price</th>
                            <th>Chỉnh sửa</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($product as $key=>$value)
                            <tr>
                                <td>{{ $key +1 }}</td>
                                <td>{{$value->id}}</td>
                                <td>{{$value->name_product}}</td>
                                <td>{{$value->Color->name_color}}</td>
                                <td>{{$value->Brand->brand_name}}</td>
                                <td>{{$value->price}}</td>
                                <td>
                                    <button class="btn btn-primary editProduct" data-toggle="modal" data-target="#edit" type="button" data-id="{{$value->id}}"><i class="fas fa-edit"></i></button>
                                    <button class="btn btn-danger deleteProduct" data-toggle="modal" data-target="#delete" type="button" data-id="{{$value->id}}"><i class="fas fa-trash-alt"></i></button>
                                </td>
                            </tr>

                        @endforeach
                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>


    {{--    edit modal--}}
    <div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Chỉnh sửa:<span class="title"></span></h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row" style="margin: 5px">
                        <div class="col-lg-12">
                              <form role="form" >
                        @csrf
                        <span class="error" style="color:green ;font-size: 1rem; "></span>
                        <fieldset class="form-group">
                            <label>Product_name</label>
                            <input class="form-control name" name="name" >
                        </fieldset>
                        <fieldset class="form-group">
                            <label>Color</label>
                            <select class="form-control color" name="color">
                                
                            </select>
                        </fieldset>
                        <fieldset class="form-group">
                            <label>brand</label>
                           <select class="form-control brand" name="brand">
                               
                           </select>
                        </fieldset>
                        <fieldset class="form-group">
                            <label>price</label>
                            <input class="form-control price" name ="price">
                        </fieldset>

                    </form>

                        <button type="button" class="btn btn-success updateProduct">Add</button>
                        <button type="reset" class="btn btn-primary">Reset</button>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    {{--    end edit modal--}}

    {{--    delete modal--}}
    <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Bạn có muốn xóa ?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body" style="margin-left: 183px;">
                    <button type="button" class="btn btn-success delete">Có</button>
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Không</button>
                    <div>
                    </div>
                </div>
            </div>

    {{--    end delete modal--}}
@endsection